name: Prueba Safari

on:

  workflow_dispatch:

jobs:
  prueba:
    runs-on: macos-latest
    name: Run Selenium tests on macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run Selenium test
        run: mvn -B -Dtest=FilmUIMultiBrowserTest test
